trace-cmd: Fix build with gcc-10
commit 0ea3f5c42ffad95ef55c8b269649a1135e5d02f9 upstream

The build fails while building with gcc-10 with the error:
multiple definition of `common_type_field'

Rename the field in trace-hist.c and trace-mem.c to satisfy gcc-10.

Link: http://lore.kernel.org/linux-trace-devel/20200417203914.26358-1-sudipm.mukherjee@gmail.com

Bug-Link: https://bugs.debian.org/957879
Signed-off-by: Sudip Mukherjee <sudipm.mukherjee@gmail.com>
Signed-off-by: Steven Rostedt (VMware) <rostedt@goodmis.org>
Signed-off-by: Sudip Mukherjee <sudipm.mukherjee@gmail.com>